spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kitchen_stories?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: password
    hikari:
      connection-test-query: SELECT 1 # Keep the connection alive if idle for a long time