spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kitchen_stories?createDatabaseIfNotExist=true&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: password
    hikari:
      connection-test-query: SELECT 1 # Keep the connection alive if idle for a long time
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method
    try-it-out-enabled: true
    tags-sorter: alpha
    filter: true
  api-docs:
    path: /api-docs
  packages-to-scan:
    - tz.co.vodacom.bujikun.kitchenstories.controller
debug: false

logging:
  level:
    org:
      springframework:
        security: TRACE
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE