package tz.co.vodacom.bujikun.thread;

import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class InitialFilesGeneratorRunnable implements Runnable {
    private String[] userFiles;

    public InitialFilesGeneratorRunnable() {
    }

    public InitialFilesGeneratorRunnable(String[] userFiles) {
        this.userFiles = userFiles;
    }

    @Override
    public void run() {
        //get a path to the current directory
        Path currentDir = Paths.get("root");
        try {
            currentDir = Files.createDirectory(currentDir);
            for (int i=0; i<2;i++){
                Path file = currentDir.resolve("file-"+i+"@autogenerated.txt");
                if(!Files.exists(file)){
                    Files.createFile(file);
                }
            }

        } catch (FileAlreadyExistsException e) {
            //dont do anything directory exists
        }catch (IOException e){
            //Serious IO Error
        }
    }
}
