package tz.co.vodacom.bujikun.thread;

import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * A runnable that will be called when the application launches to create
 * auto generated files in the root directory and also user declared files
 * provided through CLI arguments
 * @author Newton Bujiku
 * @since 2023
 */
public class InitialFilesGeneratorRunnable implements Runnable {
    private String[] userFiles;

    /**
     * Constructs a runnable passing to it user supplied CLI arguments
     * @param userFiles CLI arguments
     * @author Newton Bujiku
     * @since 2023
     */
    public InitialFilesGeneratorRunnable(String[] userFiles) {
        this.userFiles = userFiles;
    }

    /**
     * The actual run method that creates files
     * @author Newton Bujiku
     * @since 2023
     */
    @Override
    public void run() {
        //get a path to the current directory
        Path currentDir = Paths.get("root");
        try {
            currentDir = Files.createDirectory(currentDir);
            Path file = null;
            for (int i = 0; i < 2; i++) {
                file = currentDir.resolve("file-" + i + "@autogenerated.txt");
                checkAndCreate(file);
            }
            if (userFiles != null) {
                for (String fileName : userFiles) {
                    file = currentDir.resolve(fileName);
                    checkAndCreate(file);
                }
            }

        } catch (FileAlreadyExistsException e) {
            //dont do anything directory exists
        } catch (IOException e) {
            //Serious IO Error
        }
    }

    /**
     * Verifies existence of a file and creates it if does not exist
     * @param file Path to the file
     * @throws IOException Thrown when the operations fail
     * @author Newton Bujiku
     * @2023
     */
    private void checkAndCreate(Path file) throws IOException {
        if (!Files.exists(file)) {
            Files.createFile(file);
        }
    }
}
